/** LVGL UI blocks. Whole category gated by showAdvanced in toolbox. */
export const LVGL_BLOCKS = [
  {
    type: "lvgl_screen_bg",
    message0: "set screen background %1",
    args0: [{ type: "input_value", name: "COLOR", check: "Number" }],
    previousStatement: null,
    nextStatement: null,
    colour: 280,
    inputsInline: true,
    tooltip: "Hex color e.g. 0xFF0000 for red.",
  },
  {
    type: "lvgl_clear_screen",
    message0: "clear screen",
    previousStatement: null,
    nextStatement: null,
    colour: 280,
  },
  {
    type: "lvgl_label",
    message0: "show text %1 at x %2 y %3",
    args0: [
      { type: "input_value", name: "TEXT", check: "String" },
      { type: "input_value", name: "X", check: "Number" },
      { type: "input_value", name: "Y", check: "Number" },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 280,
    inputsInline: true,
  },
  {
    type: "lvgl_button",
    message0: "button %1 at x %2 y %3 size %4 x %5",
    args0: [
      { type: "input_value", name: "TEXT", check: "String" },
      { type: "input_value", name: "X", check: "Number" },
      { type: "input_value", name: "Y", check: "Number" },
      { type: "input_value", name: "W", check: "Number" },
      { type: "input_value", name: "H", check: "Number" },
    ],
    message1: "when clicked %1",
    args1: [{ type: "input_statement", name: "WHEN_CLICKED" }],
    previousStatement: null,
    nextStatement: null,
    colour: 280,
    inputsInline: true,
  },
  {
    type: "lvgl_run",
    message0: "run screen forever",
    previousStatement: null,
    nextStatement: null,
    colour: 280,
    tooltip: "Enter LVGL event loop. Blocks after this never run.",
  },
  {
    type: "lvgl_hex_color",
    message0: "color hex %1",
    args0: [{ type: "field_input", name: "HEX", text: "FF0000" }],
    output: "Number",
    colour: 20,
  },
] as const;
