from typing import Any, Callable, Iterable, Tuple

class UUID:
    def __init__(self, value: str | int | bytes) -> None: ...
    def __bytes__(self) -> bytes: ...

class BLE:
    def __init__(self) -> None: ...
    def active(self, active: bool | None = ...) -> bool: ...
    def config(self, *args: Any, **kwargs: Any) -> Any: ...
    def irq(self, handler: Callable[[int, Tuple[Any, ...]], Any] | None) -> None: ...
    def gap_advertise(
        self,
        interval_us: int | None,
        adv_data: bytes | bytearray | None = ...,
        resp_data: bytes | bytearray | None = ...,
        connectable: bool = ...,
    ) -> None: ...
    def gatts_register_services(
        self, services: Iterable[Any]
    ) -> Tuple[Tuple[int, ...], ...]: ...
    def gatts_read(self, value_handle: int) -> bytes: ...
    def gatts_write(self, value_handle: int, data: bytes | bytearray, send_update: bool = ...) -> None: ...
    def gatts_notify(self, conn_handle: int, value_handle: int, data: bytes | bytearray | None = ...) -> None: ...
    def gatts_set_buffer(self, value_handle: int, length: int, append: bool = ...) -> None: ...
    def gap_disconnect(self, conn_handle: int) -> bool: ...
