"""Minimal Python builtins stub.

Pyright ships its own `builtins`, but the in-browser stub-driven LSP has no
default typeshed, so we vendor the common surface here. Only names that show
up in casual scripts. Add more as they're missed.
"""
from typing import Any, Callable, Iterable, Iterator, Sequence, Sized

# ── Type-check / introspection ──────────────────────────────────────────────

def isinstance(obj: Any, classinfo: Any) -> bool:
    """Return True if obj is an instance of classinfo (or a tuple thereof)."""
    ...

def issubclass(cls: Any, classinfo: Any) -> bool: ...
def type(obj: Any) -> Any: ...
def callable(obj: Any) -> bool: ...
def id(obj: Any) -> int: ...
def hash(obj: Any) -> int: ...
def repr(obj: Any) -> str: ...
def dir(obj: Any = ...) -> list[str]: ...
def vars(obj: Any = ...) -> dict[str, Any]: ...
def getattr(obj: Any, name: str, default: Any = ...) -> Any: ...
def setattr(obj: Any, name: str, value: Any) -> None: ...
def hasattr(obj: Any, name: str) -> bool: ...
def delattr(obj: Any, name: str) -> None: ...

# ── I/O ─────────────────────────────────────────────────────────────────────

def print(*values: Any, sep: str = " ", end: str = "\n", file: Any = ..., flush: bool = False) -> None:
    """Print values to a stream, or to sys.stdout by default."""
    ...

def input(prompt: str = "") -> str: ...
def open(file: str, mode: str = "r", *args: Any, **kwargs: Any) -> Any: ...

# ── Numerics ────────────────────────────────────────────────────────────────

def abs(x: Any) -> Any: ...
def divmod(a: Any, b: Any) -> tuple[Any, Any]: ...
def pow(base: Any, exp: Any, mod: Any = ...) -> Any: ...
def round(number: Any, ndigits: int = ...) -> Any: ...
def min(*args: Any, key: Callable[[Any], Any] = ..., default: Any = ...) -> Any: ...
def max(*args: Any, key: Callable[[Any], Any] = ..., default: Any = ...) -> Any: ...
def sum(iterable: Iterable[Any], start: Any = 0) -> Any: ...

# ── Iteration ───────────────────────────────────────────────────────────────

def len(obj: Sized) -> int: ...
def iter(obj: Any, sentinel: Any = ...) -> Iterator[Any]: ...
def next(iterator: Iterator[Any], default: Any = ...) -> Any: ...
def range(start: int, stop: int = ..., step: int = ...) -> Sequence[int]: ...
def enumerate(iterable: Iterable[Any], start: int = 0) -> Iterator[tuple[int, Any]]: ...
def zip(*iterables: Iterable[Any]) -> Iterator[tuple[Any, ...]]: ...
def map(func: Callable[..., Any], *iterables: Iterable[Any]) -> Iterator[Any]: ...
def filter(func: Callable[[Any], bool], iterable: Iterable[Any]) -> Iterator[Any]: ...
def sorted(iterable: Iterable[Any], key: Callable[[Any], Any] = ..., reverse: bool = False) -> list[Any]: ...
def reversed(seq: Sequence[Any]) -> Iterator[Any]: ...
def all(iterable: Iterable[Any]) -> bool: ...
def any(iterable: Iterable[Any]) -> bool: ...

# ── String / bytes ──────────────────────────────────────────────────────────

def chr(i: int) -> str: ...
def ord(c: str) -> int: ...
def hex(x: int) -> str: ...
def bin(x: int) -> str: ...
def oct(x: int) -> str: ...
def format(value: Any, spec: str = "") -> str: ...
def ascii(obj: Any) -> str: ...

# ── Types (constructors) ────────────────────────────────────────────────────

class object:
    def __init__(self) -> None: ...

class int:
    def __init__(self, x: Any = ..., base: int = ...) -> None: ...
    def bit_length(self) -> int: ...
    def to_bytes(self, length: int, byteorder: str = "big") -> bytes: ...

class float:
    def __init__(self, x: Any = ...) -> None: ...
    def is_integer(self) -> bool: ...

class bool:
    def __init__(self, x: Any = ...) -> None: ...

class str:
    def __init__(self, obj: Any = ..., encoding: str = ..., errors: str = ...) -> None: ...
    def upper(self) -> str: ...
    def lower(self) -> str: ...
    def strip(self, chars: str = ...) -> str: ...
    def lstrip(self, chars: str = ...) -> str: ...
    def rstrip(self, chars: str = ...) -> str: ...
    def split(self, sep: str = ..., maxsplit: int = ...) -> list[str]: ...
    def join(self, iterable: Iterable[str]) -> str: ...
    def replace(self, old: str, new: str, count: int = ...) -> str: ...
    def startswith(self, prefix: str) -> bool: ...
    def endswith(self, suffix: str) -> bool: ...
    def find(self, sub: str) -> int: ...
    def index(self, sub: str) -> int: ...
    def format(self, *args: Any, **kwargs: Any) -> str: ...
    def encode(self, encoding: str = "utf-8", errors: str = "strict") -> bytes: ...

class bytes:
    def __init__(self, source: Any = ..., encoding: str = ..., errors: str = ...) -> None: ...
    def decode(self, encoding: str = "utf-8", errors: str = "strict") -> str: ...
    def hex(self) -> str: ...

class bytearray:
    def __init__(self, source: Any = ..., encoding: str = ..., errors: str = ...) -> None: ...

class list:
    def append(self, obj: Any) -> None: ...
    def extend(self, iterable: Iterable[Any]) -> None: ...
    def insert(self, index: int, obj: Any) -> None: ...
    def remove(self, value: Any) -> None: ...
    def pop(self, index: int = -1) -> Any: ...
    def clear(self) -> None: ...
    def index(self, value: Any) -> int: ...
    def count(self, value: Any) -> int: ...
    def sort(self, key: Callable[[Any], Any] = ..., reverse: bool = False) -> None: ...
    def reverse(self) -> None: ...
    def copy(self) -> list: ...

class tuple:
    def index(self, value: Any) -> int: ...
    def count(self, value: Any) -> int: ...

class dict:
    def keys(self) -> Iterable[Any]: ...
    def values(self) -> Iterable[Any]: ...
    def items(self) -> Iterable[tuple[Any, Any]]: ...
    def get(self, key: Any, default: Any = ...) -> Any: ...
    def pop(self, key: Any, default: Any = ...) -> Any: ...
    def update(self, other: Any) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> dict: ...
    def setdefault(self, key: Any, default: Any = ...) -> Any: ...

class set:
    def add(self, elem: Any) -> None: ...
    def remove(self, elem: Any) -> None: ...
    def discard(self, elem: Any) -> None: ...
    def pop(self) -> Any: ...
    def clear(self) -> None: ...
    def union(self, *others: Iterable[Any]) -> set: ...
    def intersection(self, *others: Iterable[Any]) -> set: ...
    def difference(self, *others: Iterable[Any]) -> set: ...

class frozenset:
    def union(self, *others: Iterable[Any]) -> frozenset: ...

# ── Exceptions (subset) ─────────────────────────────────────────────────────

class BaseException:
    args: tuple

class Exception(BaseException): ...
class ValueError(Exception): ...
class TypeError(Exception): ...
class KeyError(Exception): ...
class IndexError(Exception): ...
class AttributeError(Exception): ...
class RuntimeError(Exception): ...
class StopIteration(Exception): ...
class KeyboardInterrupt(BaseException): ...
class MemoryError(Exception): ...
class OSError(Exception): ...
class NotImplementedError(RuntimeError): ...
class ZeroDivisionError(Exception): ...

# ── Special names ───────────────────────────────────────────────────────────

def super() -> Any: ...
def globals() -> dict[str, Any]: ...
def locals() -> dict[str, Any]: ...
def compile(source: Any, filename: str, mode: str) -> Any: ...
def exec(code: Any, globals: Any = ..., locals: Any = ...) -> None: ...
def eval(source: Any, globals: Any = ..., locals: Any = ...) -> Any: ...
def breakpoint(*args: Any, **kwargs: Any) -> None: ...
