import type { Workspace } from "blockly";
import { pythonGenerator } from "blockly/python";
import { registerAllBlocks } from "../blocks";
import { resetSetup } from "../blocks/setup";

registerAllBlocks();

const HEADER = `# Generated by LEGO-Hub-blocks\n`;
const MAIN_WRAP_PRE = `\ndef main():\n`;
const MAIN_WRAP_POST = `\ntry:\n    main()\nexcept KeyboardInterrupt:\n    pass\n`;

/**
 * Generate Python source from a Blockly workspace. Wraps the user program in
 * `main()` guarded by KeyboardInterrupt so Ctrl-C in live mode stops cleanly.
 */
const DEFS_SEPARATOR = "\n\n\n";

export function workspaceToPython(workspace: Workspace): string {
  resetSetup();
  const full = pythonGenerator.workspaceToCode(workspace);
  // Blockly.Python.finish concatenates: <imports+defs>\n\n\n<code>.
  const sepIdx = full.indexOf(DEFS_SEPARATOR);
  const preamble = sepIdx >= 0 ? full.slice(0, sepIdx) : "";
  const code = sepIdx >= 0 ? full.slice(sepIdx + DEFS_SEPARATOR.length) : full;
  const indented = indent(code.replace(/\s+$/, ""));
  const bodyOrPass = indented.trim() ? indented : "    pass";
  return HEADER + preamble + MAIN_WRAP_PRE + bodyOrPass + MAIN_WRAP_POST;
}

function indent(src: string): string {
  return src
    .split("\n")
    .map((l) => (l.length ? "    " + l : l))
    .join("\n");
}
